name: Run Reindeer Games ETL

on:
  push:
    branches: 
      - main        # run when code is pushed to main
  schedule:
    - cron: '0 6 * * *'  # run every day at 6:00 UTC (adjust as needed)

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies (if you have a requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Run your ETL
      - name: Run ETL
        run: |
          python run_etl.py

      # Optional: Commit & push the new CSVs and manifest if you want them back in GitHub
      # - name: Push generated reports
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add data/reports/*
      #     git commit -m "Update reports from ETL run"
      #     git push
